<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Atrium.Abstractions\Atrium.Abstractions.csproj" />
    <ProjectReference Include="..\Atrium.Design\Atrium.Design.csproj" />
    <ProjectReference Include="..\Atrium.Modules.Hello\Atrium.Modules.Hello.csproj" />
    <ProjectReference Include="..\Atrium.Modules.Storefront\Atrium.Modules.Storefront.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
</Project>
